replicaCount: 1

image:
  repository: nginx
  tag: "590dd05c5e63a2069bd7216b4f6c5c74b732b035"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: frontend.example.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi