replicaCount: 1

image:
  repository: frontend
  tag: "66ea7d81c27d4d554d9cafad1e1f7e523d382274"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  host: frontend.example.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi