apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pankajkumarlinux/frontend:fec6cd889bab4252d18d29ebc092f0d4a13e1e6f
          ports:
            - containerPort: 5000