apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pankajkumardocker/frontend:773d4875efa6691f2639e201adabd29f07ff470c

          ports:
            - containerPort: 5000
          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
                cpu: "200m"
                memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
              initialDelaySeconds: 10
              periodSeconds: 10

            readinessProbe:
              httpGet:
              path: /
              port: 5000
              initialDelaySeconds: 5
              periodSeconds: 5